/**
 * Generated by tsnapi — public API snapshot of `preact-comark` */
// Functions
export declare function Comark({
  children,
  markdown,
  options,
  plugins,
  components: customComponents,
  componentsManifest,
  streaming,
  caret,
  className
}: ComarkProps): _$preact.JSX.Element;
export declare function ComarkClient({
  children,
  markdown,
  options,
  plugins,
  ...rest
}: ComarkProps): _$preact.JSX.Element | null;
export declare function defineComarkComponent(_?: DefineComarkComponentOptions): FunctionComponent<ComarkProps>;
export declare function defineComarkRendererComponent(_?: DefineComarkRendererOptions): FunctionComponent<ComarkRendererProps>;

// Variables
export declare const ComarkRenderer: FunctionComponent<ComarkRendererProps>;

// Re-exports
export * from "comark";